version: '3.7'

services:
  db:
    container_name: byom-api-db
    image: mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

  php:
    container_name: byom-api-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000'
    volumes:
      - ./:/app
      - ./docker/php/conf.d/byom-php.ini:/usr/local/etc/php/conf.d/byom-php.ini
      - ${LOCAL_STORAGE_PATH}:/local
    depends_on:
      - db

  nginx:
    container_name: byom-api-nginx
    image: nginx:stable-alpine
    ports:
      - '${API_PORT}:80'
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ${LOCAL_STORAGE_PATH}:/local
    depends_on:
      - db
      - php
  
volumes:
  db-data:
